name: Le pipeline

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        working-directory: volume
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        working-directory: volume
        run: cp .env.example .env

      - name: Generate app key
        working-directory: volume
        run: php artisan key:generate

      - name: Execute tests
        working-directory: volume
        run: vendor/bin/phpunit

  build-docker:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Docker
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker builder
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_WRITE }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}
