name: Le pipeline

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        working-directory: volume/app
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        working-directory: volume/app
        run: cp .env.example .env

      - name: Generate app key
        working-directory: volume/app
        run: php artisan key:generate

      - name: Execute tests
        working-directory: volume/app
        run: vendor/bin/phpunit
